version: '3.9'
services:
  frontend:
    container_name: chat-client
    command: yarn dev
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
      - ./.next:/app/.next
    networks:
      - chat-network
networks:
  chat-network:
    external:
      name: chat-app-server_default
